export const RESUME_DATA_SAMPLE = {
  basics: {
    address: "",
    city: "",
    country: "",
    cover_picture: "",
    email: "",
    firstname: "",
    headline: "",
    lastname: "",
    name: "",
    phone: "",
    picture: "",
  },
  metadata: {
    template: "Layout 1",
    variant: "",
    section_order: [
      "aboutme",
      "education",
      "experience",
      "skills",
      "languages",
      "awards",
      "hobbies",
      "courses",
      "certifications",
      "references",
      "links",
    ],
  },
  sections: {
    aboutme: {
      name: "About Me",
      columns: 1,
      visible: true,
      key: "aboutme" as const,
      content: "",
    },
    awards: {
      name: "Awards",
      columns: 1,
      visible: true,
      key: "awards" as const,
      items: [],
    },
    certifications: null,
    courses: null,
    custom: null,
    education: {
      name: "Education",
      columns: 1,
      visible: true,
      key: "education" as const,
      items: [],
    },
    experience: {
      name: "Experience",
      columns: 1,
      visible: true,
      key: "experience" as const,
      items: [],
    },
    hobbies: null,
    languages: {
      name: "Languages",
      columns: 1,
      visible: true,
      key: "languages" as const,
      items: [],
    },
    links: null,
    references: null,
    skills: {
      name: "Skills",
      columns: 1,
      visible: true,
      key: "skills" as const,
      items: [],
    },
  },
};
