#!/bin/sh -e
# The directory where backups are stored
BACKUP_DIRECTORY="/backups"

# Check if a file name was provided as a parameter
if [ $# -eq 0 ]; then
  echo "No file name provided. Please provide a file name to check."
  exit 1
fi

# The file name is taken from the first argument provided to the script
file_name="$1"

# Full path to the file
full_file_path="${BACKUP_DIRECTORY}/${file_name}"

# Check if the file exists
if [ -f "$full_file_path" ]; then
  echo "File ${file_name} exists."
else
  echo "File ${file_name} does not exist."
  exit 1
fi


echo "Dropping the database..."
PGPASSWORD="$POSTGRES_PASSWORD" dropdb "$POSTGRES_DB" -U "$POSTGRES_USER" -h "$POSTGRES_HOST" -p "$POSTGRES_PORT" --force

echo "Creating a new database..."
PGPASSWORD="$POSTGRES_PASSWORD" createdb "$POSTGRES_DB" -U "$POSTGRES_USER" -h "$POSTGRES_HOST" -p "$POSTGRES_PORT"

echo "Applying the backup to the new database..."
gunzip -c "${full_file_path}" | PGPASSWORD="$POSTGRES_PASSWORD" pg_restore -U "$POSTGRES_USER" -h "$POSTGRES_HOST" -p "$POSTGRES_PORT" -d "$POSTGRES_DB"

echo "Backup applied successfully."
