export const fontFamilies = [
  "Arial, sans-serif",
  "Courier New, monospace",
  "Georgia, serif",
  "Lucida Sans Unicode, sans-serif",
  "Tahoma, sans-serif",
  "Times New Roman, serif",
  "Trebuchet MS, sans-serif",
  "Verdana, sans-serif",
  "Open Sans, sans-serif",
  "Roboto, sans-serif",
  "Lato, sans-serif",
  "Montserrat, sans-serif",
  "Raleway, sans-serif",
  "Oswald, sans-serif",
  "Lora, serif",
  "Merriweather, serif",
  "Playfair Display, serif",
  "Source Serif Pro, serif",
  "Noto Serif, serif",
  "PT Serif, serif",
  "Arvo, serif",
  "Abril Fatface, serif",
  "Crimson Text, serif",
  "Philosopher, sans-serif",
  "Ubuntu, sans-serif",
  "Droid Sans, sans-serif",
  "Droid Serif, serif",
  "Cabin, sans-serif",
  "Fira Sans, sans-serif",
  "Poppins, sans-serif",
  "Josefin Sans, sans-serif",
  "Nunito, sans-serif",
  "Quicksand, sans-serif",
  "Varela Round, sans-serif",
  "Dosis, sans-serif",
  "Titillium Web, sans-serif",
  "Karla, sans-serif",
  "Hind, sans-serif",
  "Cuprum, sans-serif",
  "Archivo Narrow, sans-serif",
  "Alegreya Sans, sans-serif",
  "Muli, sans-serif",
  "Nunito Sans, sans-serif",
    "Asap, sans-serif",
    "Archivo, sans-serif",
    "Cairo, sans-serif",
    "Chivo, sans-serif",
    "Coda, sans-serif",
    "Cormorant, serif",
    "Cormorant Garamond, serif",
    "Cormorant Infant, serif",
    "Cormorant SC, serif",
    "Cormorant Unicase, serif",
    "Cormorant Upright, serif",
    "Crimson Pro, serif",
    "Cutive, sans-serif",
    "Cutive Mono, monospace",
    "Della Respira, serif",
    "Dosis, sans-serif",
    "Duru Sans, sans-serif",
    "Eczar, serif",
    "El Messiri, sans-serif",
    "Electrolize, sans-serif",
    "Emilys Candy, cursive",
    "Encode Sans, sans-serif",
    "Encode Sans Condensed, sans-serif",
    "Encode Sans Expanded, sans-serif",
    "Encode Sans Semi Condensed, sans-serif",
    "Encode Sans Semi Expanded, sans-serif",
    "Englebert, sans-serif",
    "Enriqueta, serif",
    "Erica One, sans-serif",
    "Esteban, serif",
    "Euphoria Script, cursive",
    "Ewert, cursive",
    "Exo, sans-serif",
    "Exo 2, sans-serif",
    "Expletus Sans, sans-serif",
    "Fahkwang, sans-serif",
    "Fanwood Text, serif",
    "Farsan, sans-serif",
    "Fascinate, cursive",
    "Fascinate Inline, cursive",
    "Faster One, cursive",
    "Fasthand, cursive",
    "Fauna One, serif",
    "Faustina, serif",
    "Federant, cursive",
    "Federo, sans-serif",
    "Felipa, cursive",
    "Fenix, serif",
    "Finger Paint, cursive",
    "Fira Mono, monospace",
    "Fira Sans Extra Condensed, sans-serif",
    "Fira Sans Semi Condensed, sans-serif",
    "Fjalla One, sans-serif",
    "Fjord One, serif",
    "Flamenco, sans-serif",
    "Flavors, cursive",
    "Fondamento, cursive",
    "Forum, cursive",
    "Francois One, sans-serif",
    "Frank Ruhl Libre, serif",
    "Freckle Face, cursive",
    "Fredericka the Great, cursive",
    "Fredoka One, cursive",
    "Freehand, cursive",
    "Fresca, sans-serif",
    "Frijole, cursive",
    "Fugaz One, cursive",
    "GFS Didot, serif",
    "GFS Neohellenic, sans-serif",
    "Gabriela, serif",
    "Gaegu, cursive",
    "Galada, cursive",
    "Galdeano, sans-serif",
    "Galindo, sans-serif",
    "Gamja Flower, cursive",
    "Gayathri, sans-serif",
    "Gelasio, serif",
    "Gentium Basic, serif",
    "Gentium Book Basic, serif",
    "Geo, sans-serif",
    "Geostar, cursive",
    "Geostar Fill, cursive",
    "Germania One, cursive",
    "Gidugu, sans-serif",
    "Gilda Display, serif",
    "Girassol, cursive",
    "Give You Glory, cursive",
    "Glass Antiqua, display",
    "Glegoo, serif",
    "Gloria Hallelujah, cursive",
    "Goblin One, cursive",
    "Gochi Hand, cursive",
    "Gorditas, cursive",
    "Gothic A1, sans-serif",
    "Goudy Bookletter 1911, serif",
    "Graduate, cursive",
    "Grand Hotel, cursive",
    "Gravitas One, cursive",
    "Great Vibes, cursive",
    "Grenze, serif",
    "Gudea, sans-serif",
    "Gugi, cursive",
    "Gupter, sans-serif",
    "Gurajada, serif",
    "Habibi, serif",
    "Halant, sans-serif",
    "Hammersmith One, sans-serif",
    "Hanalei, cursive",
    "Hanalei Fill, cursive",
    "Handlee, cursive",
    "Hanuman, sans-serif",
    "Happy Monkey, cursive",
    "Harmattan, sans-serif",
    "Headland One, serif",
    "Heebo, sans-serif",
    "Henny Penny, cursive",
    "Hepta Slab, serif",
    "Herr Von Muellerhoff, cursive",
    "Hi Melody, cursive",
    "Hind Guntur, sans-serif",
    "Hind Madurai, sans-serif",
    "Hind Siliguri, sans-serif",
    "Hind Vadodara, sans-serif",
    "Holtwood One SC, serif",
    "Homemade Apple, cursive",
    "Homenaje, sans-serif",
    "IBM Plex Mono, monospace",
    "IBM Plex Sans, sans-serif",
    "IBM Plex Sans Condensed, sans-serif",
    "IBM Plex Serif, serif",
    "IM Fell DW Pica, serif",
    "IM Fell DW Pica SC, serif",
    "IM Fell Double Pica, serif",
    "IM Fell Double Pica SC, serif",
    "IM Fell English, serif",
    "IM Fell English SC, serif",
    "IM Fell French Canon, serif",
    "IM Fell French Canon SC, serif",
    "IM Fell Great Primer, serif",
    "IM Fell Great Primer SC, serif",
    "Ibarra Real Nova, serif",
    "Iceberg, display",
    "Iceland, display",
    "Imprima, sans-serif",
    "Inconsolata, monospace",
    "Inder, sans-serif",
    "Indie Flower, cursive",
    "Inika, serif",
    "Inknut Antiqua, serif",
    "Irish Grover, cursive",
    "Istok Web, sans-serif",
    "Italiana, serif",
    "Italianno, cursive",
    "Itim, sans-serif",
    "Jacques Francois, serif",
    "Jacques Francois Shadow, display",
    "Jaldi, sans-serif",
    "Jim Nightshade, cursive",
    "Jockey One, sans-serif",
    "Jolly Lodger, cursive",
    "Jomhuria, sans-serif",
    "Jomolhari, serif",
    "Josefin Slab, serif",
    "Joti One, cursive",
    "Jua, sans-serif",
    "Judson, serif",
    "Julee, cursive",
    "Julius Sans One, sans-serif",
    "Junge, serif",
    "Jura, sans-serif",
    "Just Another Hand, cursive",
    "Just Me Again Down Here, cursive",
    "K2D, sans-serif",
    "Kadwa, serif",
    "Kalam, cursive",
    "Kameron, serif",
    "Kanit, sans-serif",
    "Kantumruy, sans-serif",
    "Karantina, sans-serif",
    "Karla, sans-serif",
    "Karma, serif",
    "Katibeh, sans-serif",
    "Kaushan Script, cursive",
    "Kavivanar, cursive",
    "Kavoon, cursive",
    "Kdam Thmor, sans-serif",
    "Keania One, cursive",
    "Kelly Slab, display",
    "Kenia, cursive",
    "Khand, sans-serif",
    "Khmer, sans-serif",
    "Khula, sans-serif",
    "Kirang Haerang, cursive",
    "Kite One, sans-serif",
    "Knewave, cursive",
    "KoHo, sans-serif",
    "Kodchasan, sans-serif",
    "Kosugi, sans-serif",
    "Kosugi Maru, sans-serif",
    "Kotta One, serif",
    "Koulen, sans-serif",
    "Kranky, cursive",
    "Kreon, serif",
    "Kristi, cursive",
    "Krona One, sans-serif",
    "Krub, sans-serif",
    "Kufam, sans-serif",
    "Kumar One, display",
    "Kumar One Outline, display",
    "Kurale, serif",
    "La Belle Aurore, cursive",
    "Laila, sans-serif",
    "Lakki Reddy, cursive",
    "Lalezar, cursive",
    "Lancelot, cursive",
    "Lateef, cursive",
    "Lato, sans-serif",
    "League Script, cursive",
    "Leckerli One, cursive",
    "Ledger, serif",
    "Lekton, sans-serif",
    "Lemon, display",
    "Lemonada, cursive",
    "Lexend Deca, sans-serif",
    "Lexend Exa, sans-serif",
    "Lexend Giga, sans-serif",
    "Lexend Mega, sans-serif",
    "Lexend Peta, sans-serif",
    "Lexend Tera, sans-serif",
    "Lexend Zetta, sans-serif",
    "Libre Barcode 128, cursive",
    "Libre Barcode 128 Text, cursive",
    "Libre Barcode 39, cursive",
    "Libre Barcode 39 Extended, cursive",
    "Libre Barcode 39 Extended Text, cursive",
    "Libre Barcode 39 Text, cursive",
    "Libre Baskerville, serif",
    "Libre Caslon Display, serif",
    "Libre Caslon Text, serif",
    "Libre Franklin, sans-serif",
    "Life Savers, cursive",
    "Lilita One, cursive",
    "Lily Script One, cursive",
    "Limelight, cursive",
    "Linden Hill, serif",
    "Literata, serif",
    "Liu Jian Mao Cao, cursive",
    "Livvic, sans-serif",
    "Lobster, cursive",
    "Lobster Two, cursive",
    "Londrina Outline, cursive",
    "Londrina Shadow, display",
    "Londrina Sketch, cursive",
    "Londrina Solid, cursive",
    "Long Cang, sans-serif",
    "Lora, serif",
    "Love Ya Like A Sister, cursive",
    "Loved by the King, cursive",
    "Lovers Quarrel, cursive",
    "Luckiest Guy, cursive",
    "Lusitana, serif",
    "Lustria, serif",
    "M PLUS 1p, sans-serif",
    "M PLUS Rounded 1c, sans-serif",
    "Ma Shan Zheng, cursive",
    "Macondo, cursive",
    "Macondo Swash Caps, cursive",
    "Mada, sans-serif",
    "Magra, sans-serif",
    "Maiden Orange, cursive",
    "Maitree, sans-serif",
    "Major Mono Display, monospace",
    "Mako, sans-serif",
    "Mali, cursive",
    "Mallanna, sans-serif",
    "Mandali, sans-serif",
    "Manjari, sans-serif",
    "Manrope, sans-serif",
    "Mansalva, cursive",
    "Manuale, serif",
    "Marcellus, serif",
    "Marcellus SC, serif",
    "Marck Script, cursive",
    "Margarine, cursive",
    "Markazi Text, serif",
    "Marko One, serif",
    "Marmelad, sans-serif",
    "Martel, serif",
    "Martel Sans, sans-serif",
    "Marvel, sans-serif",
    "Mate, serif",
    "Mate SC, serif",
    "Maven Pro, sans-serif",
    "McLaren, cursive",
    "Meddon, cursive",
    "MedievalSharp, cursive",
    "Medula One, cursive",
    "Meera Inimai, sans-serif",
    "Megrim, cursive",
    "Meie Script, cursive",
    "Merienda, cursive",
    "Merienda One, cursive",
    "Merriweather, serif",
    "Merriweather Sans, sans-serif",
    "Metal, cursive",
    "Metal Mania, display",
    "Metamorphous, cursive",
    "Metrophobic, sans-serif",
    "Michroma, sans-serif",
    "Milonga, cursive",
    "Miltonian, cursive",
    "Miltonian Tattoo, cursive",
    "Mina, sans-serif",
    "Miniver, display",
    "Miriam Libre, sans-serif",
    "Mirza, serif",
    "Miss Fajardose, cursive",
    "Mitr, sans-serif",
    "Modak, display",
    "Modern Antiqua, display",
    "Mogra, cursive",
    "Molengo, sans-serif",
    "Molle, cursive",
    "Monda, sans-serif",
    "Monofett, cursive",
    "Monoton, cursive",
    "Monsieur La Doulaise, cursive",
    "Montaga, serif",
    "Montez, cursive",
    "Montserrat, sans-serif",
    "Montserrat Alternates, sans-serif",
    "Montserrat Subrayada, sans-serif",
    "Moul, sans-serif",
    "Moulpali, sans-serif",
    "Mountains of Christmas, cursive",
    "Mouse Memoirs, cursive",
    "Mr Bedfort, cursive",
    "Mr Dafoe, cursive",
    "Mr De Haviland, cursive",
    "Mrs Saint Delafield, cursive",
    "Mrs Sheppards, cursive",
    "Mukta, sans-serif",
    "Mukta Mahee, sans-serif",
    "Mukta Malar, sans-serif",
    "Mukta Vaani, sans-serif",
    "Mulish, sans-serif",
    "MuseoModerno, sans-serif",
    "Mystery Quest, cursive",
    "NTR, sans-serif",
    "Nanum Brush Script, cursive",
    "Nanum Gothic, sans-serif",
    "Nanum Gothic Coding, monospace",
    "Nanum Myeongjo, serif",
    "Nanum Pen Script, cursive",
    "Nerko One, cursive",
    "Neucha, cursive",
    "Neuton, serif",
    "New Rocker, display",
    "News Cycle, sans-serif",
    "Niconne, cursive",
    "Niramit, sans-serif",
    "Nixie One, cursive",
    "Nobile, sans-serif",
    "Nokora, serif",
    "Norican, cursive",
    "Nosifer, display",
    "Notable, sans-serif",
    "Nothing You Could Do, cursive",
    "Noticia Text, serif",
    "Noto Sans, sans-serif",
    "Noto Serif, serif",
    "Nova Cut, display",
    "Nova Flat, display",
    "Nova Mono, monospace",
    "Nova Oval, display",
    "Nova Round, display",
    "Nova Script, cursive",
    "Nova Slim, display",
    "Nova Square, display",
    "Numans, sans-serif",
    "Nunito, sans-serif",
    "Nunito Sans, sans-serif",
    "Odibee Sans, cursive",
    "Odor Mean Chey, cursive",
    "Offside, display",
    "Old Standard TT, serif",
    "Oldenburg, cursive",
    "Oleo Script, cursive",
    "Oleo Script Swash Caps, cursive",
    "Open Sans, sans-serif",
    "Open Sans Condensed, sans-serif",
    "Oranienbaum, serif",
    "Orbitron, sans-serif",
    "Oregano, cursive",
    "Orienta, sans-serif",
    "Original Surfer, cursive",
    "Oswald, sans-serif",
    "Over the Rainbow, cursive",
    "Overlock, sans-serif",
    "Overlock SC, sans-serif",
    "Overpass, sans-serif",
    "Overpass Mono, monospace",
    "Ovo, serif",
    "Oxanium, sans-serif",
    "Oxygen, sans-serif",
    "Oxygen Mono, monospace",
    "PT Mono, monospace",
    "PT Sans, sans-serif",
    "PT Sans Caption, sans-serif",
    "PT Sans Narrow, sans-serif",
    "PT Serif, serif",
    "PT Serif Caption, serif",
    "Pacifico, cursive",
    "Padauk, sans-serif",
    "Palanquin, sans-serif",
    "Palanquin Dark, sans-serif",
    "Pangolin, sans-serif",
    "Paprika, display",
    "Parisienne, cursive",
    "Passero One, cursive",
    "Passion One, cursive",
    "Pathway Gothic One, sans-serif",
    "Patrick Hand, cursive",
    "Patrick Hand SC, cursive",
    "Pattaya, sans-serif",
    "Patua One, cursive",
    "Pavanam, sans-serif",
    "Paytone One, sans-serif",
    "Peddana, sans-serif",
    "Peralta, cursive",
    "Permanent Marker, cursive",
    "Petit Formal Script, cursive",
    "Petrona, sans-serif",
    "Philosopher, sans-serif",
    "Piedra, cursive",
    "Pinyon Script, cursive",
    "Pirata One, cursive",
    "Plaster, display",
    "Play, sans-serif",
    "Playball, cursive",
    "Playfair Display, serif",
    "Playfair Display SC, serif",
    "Podkova, serif",
    "Poiret One, display",
    "Poller One, display",
    "Poly, sans-serif",
    "Pompiere, cursive",
    "Pontano Sans, sans-serif",
    "Poor Story, cursive",
    "Poppins, sans-serif",
    "Port Lligat Sans, sans-serif",
    "Port Lligat Slab, serif",
    "Pragati Narrow, sans-serif",
    "Prata, serif",
    "Preahvihear, sans-serif",
    "Press Start 2P, cursive",
    "Pridi, serif",
    "Princess Sofia, cursive",
    "Prociono, serif",
    "Prompt, sans-serif",
    "Prosto One, cursive",
    "Proza Libre, sans-serif",
    "Public Sans, sans-serif",
    "Puritan, sans-serif",
    "Purple Purse, cursive",
    "Quando, serif",
    "Quantico, sans-serif",
    "Quattrocento, serif",
    "Quattrocento Sans, sans-serif",
    "Questrial, sans-serif",
    "Quicksand, sans-serif",
    "Quintessential, cursive",
    "Qwigley, cursive",
    "Racing Sans One, sans-serif",
    "Radley, serif",
    "Rajdhani, sans-serif",
    "Rakkas, cursive",
    "Raleway, sans-serif",
    "Raleway Dots, display",
    "Ramabhadra, sans-serif",
    "Ramaraja, sans-serif",
    "Rambla, sans-serif",
    "Rammetto One, cursive",
    "Ranchers, cursive",
    "Rancho, cursive",
    "Ranga, cursive",
    "Rasa, serif",
    "Rationale, sans-serif",
    "Ravi Prakash, sans-serif",
    "Red Hat Display, sans-serif",
    "Red Hat Text, sans-serif",
    "Red Rose, cursive",
    "Reem Kufi, sans-serif",
    "Reenie Beanie, cursive",
    "Revalia, cursive",
    "Rhodium Libre, sans-serif",
    "Ribeye, cursive",
    "Ribeye Marrow, cursive",
    "Righteous, cursive",
    "Risque, cursive",
    "Roboto, sans-serif",
    "Roboto Condensed, sans-serif",
    "Roboto Mono, monospace",
    "Roboto Slab, serif",
    "Rochester, cursive",
    "Rock Salt, cursive",
    "Rokkitt, serif",
    "Romanesco, cursive",
    "Ropa Sans, sans-serif",
    "Rosario, sans-serif",
    "Rosarivo, serif",
    "Rouge Script, cursive",
    "Rowdies, sans-serif",
    "Rozha One, serif",
    "Rubik, sans-serif",
    "Rubik Mono One, sans-serif",
    "Ruda, sans-serif",
    "Rufina, serif",
    "Ruge Boogie, cursive",
    "Ruluko, cursive",
    "Rum Raisin, cursive",
    "Ruslan Display, display",
    "Russo One, sans-serif",
    "Ruthie, cursive",
    "Rye, cursive",
    "Sacramento, cursive",
    "Sahitya, serif",
    "Sail, cursive",
    "Saira, sans-serif",
    "Saira Condensed, sans-serif",
    "Saira Extra Condensed, sans-serif",
    "Saira Semi Condensed, sans-serif",
    "Saira Stencil One, sans-serif",
    "Salsa, cursive",
    "Sanchez, serif",
    "Sancreek, cursive",
    "Sansita, sans-serif",
    "Sarabun, sans-serif",
    "Sarala, sans-serif",
    "Sarina, cursive",
    "Sarpanch, sans-serif",
    "Satisfy, cursive",
    "Sawarabi Gothic, sans-serif",
    "Sawarabi Mincho, serif",
    "Scada, sans-serif",
    "Scheherazade, serif",
    "Schoolbell, cursive",
    "Scope One, sans-serif",
    "Seaweed Script, cursive",
    "Secular One, sans-serif",
    "Sedgwick Ave, cursive",
    "Sedgwick Ave Display, cursive",
    "Sevillana, cursive",
    "Seymour One, sans-serif",
    "Shadows Into Light, cursive",
    "Shadows Into Light Two, cursive",
    "Shanti, sans-serif",
    "Share, sans-serif",
    "Share Tech, sans-serif",
    "Share Tech Mono, monospace",
    "Shojumaru, cursive",
    "Short Stack, cursive",
    "Shrikhand, cursive",
    "Siemreap, sans-serif",
    "Sigmar One, cursive",
    "Signika, sans-serif",
    "Signika Negative, sans-serif",
    "Simonetta, serif",
    "Single Day, cursive",
    "Sintony, sans-serif",
    "Sirin Stencil, display",
    "Six Caps, sans-serif",
    "Skranji, cursive",
    "Slabo 13px, serif",
    "Slabo 27px, serif",
    "Slackey, cursive",
    "Smokum, cursive",
    "Smythe, cursive",
    "Sniglet, cursive",
    "Snippet, sans-serif",
    "Snowburst One, display",
    "Sofadi One, cursive",
    "Sofia, cursive",
    "Solway, serif",
    "Song Myung, sans-serif",
    "Sonsie One, cursive",
    "Sora, sans-serif",
    "Sorts Mill Goudy, serif",
    "Source Code Pro, monospace",
    "Source Sans Pro, sans-serif",
    "Source Serif Pro, serif",
    "Space Mono, monospace",
    "Special Elite, cursive",
    "Spectral, serif",
    "Spectral SC, serif",
    "Spicy Rice, cursive",
    "Spinnaker, sans-serif",
    "Spirax, cursive",
    "Squada One, cursive",
    "Sree Krushnadevaraya, sans-serif",
    "Sriracha, cursive",
    "Srisakdi, sans-serif",
    "Staatliches, sans-serif",
    "Stalemate, cursive",
    "Stalinist One, cursive",
    "Stardos Stencil, display",
    "Stint Ultra Condensed, sans-serif",
    "Stint Ultra Expanded, sans-serif",
    "Stoke, serif",
    "Strait, sans-serif",
    "Stylish, sans-serif",
    "Sue Ellen Francisco, cursive",
    "Suez One, serif",
    "Sulphur Point, sans-serif",
    "Sumana, serif",
    "Sunflower, sans-serif",
    "Sunshiney, cursive",
    "Supermercado One, cursive",
    "Sura, sans-serif",
    "Suranna, sans-serif",
    "Suravaram, sans-serif",
    "Swanky and Moo Moo, cursive",
    "Syncopate, sans-serif",
    "Tajawal, sans-serif",
    "Tangerine, cursive",
    "Taprom, sans-serif",
    "Tauri, sans-serif",
    "Taviraj, serif",
    "Teko, sans-serif",
    "Telex, sans-serif",
    "Tenali Ramakrishna, sans-serif",
    "Tenor Sans, sans-serif",
    "Text Me One, sans-serif",
    "Thasadith, sans-serif",
];
