## Docker command

default:
  just --list

up:
  docker compose up -d

kill:
  docker compose kill

build:
  docker compose build

ps:
  docker compose ps

exec *args:
  docker compose exec humantree_app {{args}}

logs *args:
    docker compose logs {{args}} -f

mm *args:
  docker compose exec humantree_app alembic revision --autogenerate -m "{{args}}"

migrate:
  docker compose exec humantree_app alembic upgrade head

downgrade *args:
  docker compose exec humantree_app alembic downgrade {{args}}

ruff *args:
  docker compose exec humantree_app ruff {{args}} src
  docker compose exec humantree_app ruff format src

lint:
  just ruff --fix

backup:
  docker compose exec humantree_db scripts/backup
  
# examples:
# "just get-backup dump_name_2021-01-01..backup.gz" to copy particular backup
# "just get-backup" to copy directory (backups) with all dumps
get-backup *args:
  docker cp humantree_db:/backups/{{args}} ./{{args}}

restore *args:
    docker compose exec humantree_db scripts/restore {{args}}

test *args:
    docker compose exec humantree_app pytest {{args}}