service: serverless-humantree
frameworkVersion: "3"
useDotenv: true
provider:
  name: aws
  region: ap-southeast-1
  stage: dev
  runtime: python3.11

functions:
  api:
    handler: src.main.handler
    events:
      - httpApi: "*"
plugins:
  - serverless-python-requirements
  - serverless-dotenv-plugin
